### ISSUE TITLE
Allow for Company activities

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1041]
Jealy/C4 had the idea to couple activities to companies. This would suitable for some career activities.
Then you could also have an overview for solely external activities.

**Comment by mstruijs** [comment]
What are the capabilities this link look should have? Are those listed (plus CRUD for the links) all of them? I would go for the following approach:

1. Use the activity category infrastructure from #749 (I'm assuming here this solution is many to many (haven't really looked at the code), as it is useful for activities to have categories across multiple dimensions: lunch-lecture, online/offline, carreer-related, etc. In other words, I'm basically assuming the categories work like tags or labels),
2. Define and maintain an unique (bidirectional?) mapping from companies to categories and automagically create the categories. (Not sure a cronjob would work. But I think you can just lazily create the category whenever someone asks what the category of a given company is. ) Might also be useful to implement a "Does this tag belong to some company?" query, which can answer "yes" or "Maybe, but if it does, nobody told me". The latter answer is as good as "no", because the mapping is maintained in only 1 place and you can't find it there, it might as well not exist. There's probably a fancy name for this type of scheme, but I don't know that name.
3. Go wild on the frontend. Make an overview for a specific company? Query for the tag of the company, query for all activities with the tag. Associate an activity with a company? Query for tag of the company, add tag to activity. 

Most other approaches I can come up with seem to boil down to "activity categories but only for companies", which would violate DRY more than this approach, I think. As this issue doesn't seem very urgent, a dependency on #749 isn't a big problem either.

**Comment by cebgewis** [comment]
Personally I was thinking that you could use a similar approach as for connecting activities to committees. You can use a list where you can select a company. Regarding the front-end, you could also use the same style as for committee activities.

Regarding the #749 issue, you should indeed have a seperate category for external activities.

Good to see that you guys are working on this, looking forward to seeing all your progress and let me know if you have any questions!
