### ISSUE TITLE
Add GM committees somewhere more visible on the website

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1075]
_Hello dear web committee, I see that I can use markdown here, so I will!_

### Situation
I was reading the minutes of the 1539th board meeting on the website, and saw that Max's PR for the RvA was accepted. Naturally, as a former member of the RvA, I wanted to know what that meant. I went to the committee page, cause I taught his PR had to do with that, but that was not the case. To find info about the RvA, I first had to go to the page of a member of the RvA, and then click under "membership of committees and fraternities" to go to the RvA page.

### Problem
I think it is hard for GEWIS members to find people that are in GM committees, like the RvA or the Audit Commission. This info should be more easily available than either knowing someone that is in these group and going to their profile, or looking at old GM minutes to find who is a member, in my opinion.

### Propsed solution
Since pages already exist for these groups (as demonstrated by the fact you can find them under memberships at people's profile), maybe a link from somewhere could be added. The membership page tells us that it is either a committee or a fraternity, so then I would think adding them as a special section on the committee page would be nicest. If you have any other ideas (or think it is not needed), also do let me know!

_This was everything! <3_

**Comment by tomudding** [comment]
I think we will condense the menu (Committees / Fraternities) under 'Association' into a submenu containing Committees, Fraternities, and a new third page with the special organs.

Do you think that will improve discoverability of these special organs?

**Comment by LeonVreling** [comment]
I think that would be a good addition to the website, since then these organs can be found somewhere.

To me, however, now it sounds like a sub-sub-menu, which we don't have anywhere on the website atm (afaik). I was wondering how it will look like in the end, but I'm sure you will make it look fine 😁

**Comment by tomudding** [comment]
> To me, however, now it sounds like a sub-sub-menu, which we don't have anywhere on the website atm (afaik).

I wouldn't call it a sub-sub-menu myself, but I get where you are coming from. We are currently changing some other things in the menu, which requires an extra level to the menu, hence we plan to also make the change I mentioned in my previous comment.

**Comment by jealyvda** [comment]
Dear Web Committee,

I just stumbled upon this issue. The AV organs are also mentioned under the Member page > Organs, so with the board we  agreed that we do not see the need to actually add this feature, as it is also not really of relevance to externals.

The reason I stumbled upon this issue is actually because of another request that Irne had send an email about earlier, namely the wellbeing page! We agree with Leon that the association tab is becoming a bit too big so we discussed this with the board and came to the following suggestion:

> Board
> Committees
> Fraternities
> Honorary People (this will be a new page that displays the honorary members and the contributors)
> GEWIS Song
> Regulations
> Useful Information
>>>> Links
>>>> Wellbeing
>>>> FAQ
> Contact

This means that the GM page can be removed (we already saved the information and Max look into displaying it elsewhere) and that we can create a sub-menu for Useful Information with the mentioned three subtabs.

Would it be possible for you to implement this change? Perhaps it could be wise to create a new issue for it.

With kind regards, Jealy van den Aker

It would be ideal if the board could update the Honorary People tab, since this will have to be updated rather frequently. Perhaps we could also update it from the Admin Pages feature?

**Comment by tomudding** [comment]
Dear @jealyvda and @Irne,

Thank you for your suggestion. Your solution does appear to be more useful to our members and external users of the website. I'll see what we can do for the menu to incorporate all changes and have it remain useful for everyone.

I have one question regarding
> It would be ideal if the board could update the Honorary People tab, since this will have to be updated rather frequently.

What do you exactly want to update? You can define and add a `nav` (`nav-pills`) similar to the one present on the `/links/*` pages to distinguish between Honorary People and Contributors if you need two separate pages (e.g., a new `/vereniging/ereleden` and the currently existing `/vereniging/donateurs`). As long as there is one "main" page (i.e., the 'Honorary People'-page, as that text will be displayed in the menu) we can just use that one.

Tom

**Comment by jealyvda** [comment]
Dear Tom,

We could indeed use a similar set-up as for the links page. However the problem is that the script tags are automatically removed, which is rather inconvenient.. Perhaps there would be another solution to not having these script tags removed for these specific pages?

Jealy
