### ISSUE TITLE
Add Referer-Policy header

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1299]
I propose setting it to either `strict-origin-when-cross-origin`.
This should be adjusted in the nginx.conf

**Comment by tomudding** [comment]
We should also add `Permissions-Policy` (with `interest-cohort=()`, because Google).

**Comment by Koen1999** [comment]
@tomudding , I'm not really sure what to do with all other possible fields in the Permissions-Policy

**Comment by tomudding** [comment]
> @tomudding , I'm not really sure what to do with all other possible fields in the Permissions-Policy

It is a bit complicated since it is still "experimental". I would prefer if we at least add the anti-FLoC part (`interest-cohort`) and then we can probably add a few basic things which we now that at least now we will not be using. Any more complex permissions are something for the future.

I think something like this will work nicely:

```
Permissions-Policy: accelerometer=("https://www.youtube-nocookie.com" "https://player.vimeo.com"), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=("https://www.youtube-nocookie.com" "https://player.vimeo.com"), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self "https://www.youtube-nocookie.com" "https://player.vimeo.com"), geolocation=(), gyroscope=("https://www.youtube-nocookie.com" "https://player.vimeo.com"), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=("https://www.youtube-nocookie.com" "https://player.vimeo.com"), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-write=(self), interest-cohort=()
```

It disables all currently "standard" directives (+ `interest-cohort`), except for:
- **accelerometer**
- **encrypted-media**
- **_fullscreen_**
- **gyroscope**
- **picture-in-picture**
- _clipboard-write_

**bold** is for YouTube and Vimeo embeds, _italic_ is for self (i.e. https://gewis.nl).
