### ISSUE TITLE
Show inactive fraternity members on fraternity page

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1854]
### What would you like?

Show both inactive members on fraternity pages such as https://gewis.nl/en/association/fraternity/I.V.V as is also done for https://gewis.nl/en/organs/view/93 if the user is signed in

### Why is this needed?

Because it makes it easier to see who is and who is no longer considered an inactive fraternity member. 

### Other information

- In [GH-1497](https://github.com/GEWIS/gewisweb/pull/1497/files#diff-5232a304714c139f4136d63c1f0d0c2b0de5ad9b7005687d09ce2d2af58731a7R32), inactive members were added to `decision/organ/show.phtml`. However, `frontpage/organ/organ.phtml` only considers active members: https://github.com/GEWIS/gewisweb/blob/8b3cbe186f92b3294d9b6ad260e8970fefe420b9/module/Frontpage/view/frontpage/organ/organ.phtml#L150<br/>Unless it is a fraternity that was abrogated; then, it shows all members

- Risks to be considered: 404 hyperlinks if a membership has expired and the inactive fraternity member was not formally discharged

- Like the active members, it should only be visible for signed-in users.

**Comment by tomudding** [comment]
I do agree that we should add inactive fraternity members to the page. However, I do not yet know how to do that without creating a mess on the page. Perhaps they need to be in a smaller font, or we need to rethink our whole idea of how we display organs.

---

> Unless it is a fraternity that was abrogated; then, it shows all members

The original reasoning for this (although not present in the commit message or GH-1796 description) is to prevent too much clutter on that page. _When_ you need to know about an old member you go to the full page instead of having many names on the page.
