### ISSUE TITLE
Photo page is annoying

### ISSUE THREAD

**Issue by tuupke** [GEWIS/gewisweb#482]
At first the photo page seems great, the animation has a nice look to it, but after using it for a while it gets really on your nerves.

When clicking on a photo before the page is fully loaded results in it being replaced by another photo right when you are clicking on the ony you wanted. That jumping around makes it just look really messy. 

Maybe consider having a more predefined width, to just make the images load more regularly instead of jumping all over the page. Or increase the number of photos on a single page since the sheer amount of times one has to look at that animation playing out is way way way to much (especially for large albums). Or maybe even choose a more html4 styled photo viewer.

**Comment by jszanto** [comment]
Additionally there also is random whitespace between photos on some pages, example: https://www.gewis.nl/photo/album/297

**Comment by kokx** [comment]
That is not so random. It is because a few photos have a different aspect ratio. Most photo's adhere to the same aspect ratio. But some photo's are cropped differently, which makes their aspect ratio weird.

Lately, GEFLITST has tried to keep the same aspect ratio. Thus, in recent albums this shouldn't be that much of a problem.

It does look ugly however.

**Comment by tuupke** [comment]
Sure, geflits may now be using the same aspect ratio, but if history has learned us anything is that the website will be online quite long before being replaced, so this forces either geflitst to keep using the same aspect ratio xor the whitespace(s) to appear eventually.

**Comment by jszanto** [comment]
The whitespace issue has nothing to do with the aspect ratios. The website can perfectly well handle photos with different aspect ratios. What you see here is a bug in the layout code. There is a feature which is supposed to make photos which have been a photo of the week stand out a bit. This is done my making them larger then the other photos. It is supposed to look approximately like this:

![screenshot from 2016-02-07 23 34 07](https://cloud.githubusercontent.com/assets/7968933/12875849/92da0c42-cdf3-11e5-8bd7-29e23d956160.png)


However it seems like something is going wrong, possibly due to the website not sizing the photos correctly.

**Comment by kokx** [comment]
So this will probably be solved by using the larger thumbnail for these photo's?

**Comment by jszanto** [comment]
It actually is using the larger thumbnail at the moment, which causes the problem. A few changes to the CSS will probably fix it.

**Comment by jszanto** [comment]
#517 didn't say it fixes this issue.

**Comment by Mesoptier** [comment]
Ik kan hier ook nog wel naar kijken, wanneer ik met de foto pagina aan de slag ga.

**Comment by jszanto** [comment]
👍

**Comment by jszanto** [comment]
I think this was sort of fixed by c0b6fe1. @tuupke can you test the website to verify that your annoyances are resolved?

**Comment by tuupke** [comment]
Much much much better; there are still some issues though. Looking at the photo page now will yield an empty space since there is a title that takes 2 lines of space.

![image](https://cloud.githubusercontent.com/assets/2218324/13716124/6851d270-e7d9-11e5-8651-b79ab1279a21.png)
