### ISSUE TITLE
Fix former Dutch URLs

### ISSUE THREAD

**Issue by BorBorBor** [GEWIS/gewisweb#532]
e.g. gewis.nl/fotos, /activiteiten, /onderwijs are all dead now but should point to their new English couterparts

**Comment by kokx** [comment]
It is probably easiest if this is fixed in the apache config. There is a `/etc/apache2/redirects.conf` that can easily be used for this purpose.

**Comment by Mesoptier** [comment]
Maybe we could just add Dutch paths, instead of redirecting them to their English counterparts. So `/fotos` and `/photos` would both point to the same controller/action. This could also automatically set the language (maybe). And if all URLs in views are generated by a view helper, these URLs can all be i18ned.

**Comment by gafderks** [comment]
Do we still need this?

**Comment by Koen1999** [comment]
I don't think this problem still exists.
