### ISSUE TITLE
Display activities which the user is signed up for

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#725]

**Comment by mstruijs** [comment]
Additionally, create functionality to export the activities to a calendar (.ics) format.

**Comment by Staartvin** [comment]
Should this be displayed on the activities page or on the profile page?

**Comment by jszanto** [comment]
I think the activities page would be the most logical place for this, not quite sure how it should fit in the design though. Sidebar? Top of the page? Seperate page?

**Comment by Staartvin** [comment]
I agree that the activities page is the most logical place, but care should be taken that does not become too cluttered. Perhaps a button on the side that opens a pop-up dialog showing your signups for the currently active activities? Additionally, should the admin interface show an overview of signup activities per user?

**Comment by mstruijs** [comment]
Only showing the list after a button press doesn't seem to be a good idea,
as we want to provide a convinient overview. The top seems to be the most
logical place, as verifying the activities signed up for could be a
reasonable step before viewing new activities. We can ensure this doesn't
explode by only showing the first X events and reveal more only at a button
press.

I don't see the use case for a activities by  joined user query for anyone
except the user. The data is available (public, even), so I don't see why
we want to add this to the admin.



Op 1 apr. 2017 18:06 schreef "Staartvin" <notifications@github.com>:

I agree that the activities page is the most logical place, but care should
be taken that does not become too cluttered. Perhaps a button on the side
that opens a pop-up dialog showing your signups for the currently active
activities? Additionally, should the admin interface show an overview of
signup activities per user?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/GEWIS/gewisweb/issues/725#issuecomment-290929498>, or mute
the thread
