### ISSUE TITLE
No support for AVCs

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#774]
When you go to the URL of an AVC, they do not have a page, but they appear, including an URL, on the page of somebody's profile. There should be a page for those.

**Comment by Kevinjil** [comment]
This can be easily fixed by adding 'avc' to
https://github.com/GEWIS/gewisweb/blob/b573999874210d5cd7ca2540b52952747c5b3fb6/module/Frontpage/config/module.config.php#L51
You can currently view the AVC page by just replacing 'avc' with 'committee' in the URL.

Is there a specific reason why the AVCs haven't been added there?
