### ISSUE TITLE
Improve findability of links page

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#843]
As we received the request to build a page with links which was already there, maybe the visibility of it is bad. Currently it is listed under 'Association', but there may be a more logical location.

**Comment by BorBorBor** [comment]
Maybe it should be updated (by the board) as well. This hasn't changed since the old website… 

What I notice so far (looking briefly): Asset | SBIT is not a sister association so should not be listed there. There is also an inconsistency in the headers of the association lists. Either the one should be changed to 'nichtjesverenigingen' or the other should be renamed 'other assocations for mathematics or CS'.

Maybe even better is to do something like 'Other member organizations of the WISO' and 'Other member organizations of the FSE'

**Comment by Koen1999** [comment]
I think this issue is resolved. The links page has been added to the members panel. The board has also updated the contents.
