### ISSUE TITLE
Photo: segfault caused by zend isImage()

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#91]
Investigate what's exactly causing this and mitigate this problem.

**Comment by stefanmajoor** [comment]
First of all, this is not a bug in our code, because (1) it is triggered by ZF, and segfaults are only thrown due to bugs in PHP.

So, this is not a bug that needs fixing, but rather needs a working work around solution. A quick google search gave this:

https://github.com/zendframework/zf2/issues/6493

So, basicly add "'magicFile' => false" to the options, and it will probably work again

**Comment by jszanto** [comment]
that's why it said "mitigate"

**Comment by jszanto** [comment]
Seems like this was just fixed in php 2 weeks ago https://bugs.php.net/bug.php?id=68214
