### ISSUE TITLE
Add forward on member page

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisweb#944]
As kind request by the committee Stijl: add a button on the [gewis.nl/member](https://gewis.nl/member) page that forwards you to [gewis.nl/~stijl](https://gewis.nl/~stijl) (in the future [gewis.nl/stijl](https://gewis.nl/stijl)) where the files regarding the corporate design are located.

**Comment by Koen1999** [comment]
I don't really see how this is not an easy-fix.

**Comment by kokx** [comment]
Because I don't think this should be directly on the members page at all. It should be in our public archive, with all other documents like this.

So yes, technically an easy fix. But the easy-fix tag is for things that can be readily done by anyone. Not things that may still have some discussion involved.

**Comment by Gijsdeman** [comment]
The thing is that not only files are located on this page. If that were the case we would only add it to the public archives. However, the Stijl webpage also contains a lot of easily accessible readme files and version updates that Stijl would like to make accessible through the website instead of through another file in the public archives. To get a good view of what we are trying to achieve, you can have a look at [gewis.nl/~stijl](url).
